"""
用于生成智能体和项目图标与颜色的工具。
"""

import json
import traceback

from loguru import logger

from core.services.llm import make_llm_api_call

# Lucide React 图标（硬编码以提高性能）
RELEVANT_ICONS = [
    "accessibility",
    "activity",
    "air-vent",
    "airplay",
    "alarm-clock",
    "album",
    "align-left",
    "align-right",
    "ambulance",
    "ampersand",
    "anchor",
    "angry",
    "antenna",
    "anvil",
    "aperture",
    "app-window",
    "apple",
    "archive",
    "armchair",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-up",
    "asterisk",
    "at-sign",
    "atom",
    "audio-lines",
    "award",
    "axe",
    "axis3d",
    "baby",
    "backpack",
    "badge",
    "baggage-claim",
    "ban",
    "banana",
    "bandage",
    "banknote",
    "barcode",
    "baseline",
    "bath",
    "battery",
    "battery-charging",
    "beaker",
    "bean",
    "bed",
    "beef",
    "beer",
    "bell",
    "biceps-flexed",
    "bike",
    "binary",
    "binoculars",
    "biohazard",
    "bird",
    "bitcoin",
    "blend",
    "blinds",
    "blocks",
    "bluetooth",
    "bold",
    "bolt",
    "bomb",
    "bone",
    "book",
    "bookmark",
    "boom-box",
    "bot",
    "box",
    "boxes",
    "braces",
    "brackets",
    "brain",
    "brick-wall",
    "briefcase",
    "bring-to-front",
    "brush",
    "bug",
    "building",
    "bus",
    "cable",
    "cable-car",
    "cake",
    "calculator",
    "calendar",
    "camera",
    "candy",
    "cannabis",
    "captions",
    "car",
    "caravan",
    "carrot",
    "case-sensitive",
    "cassette-tape",
    "cast",
    "castle",
    "cat",
    "cctv",
    "chart-bar",
    "chart-pie",
    "check",
    "chef-hat",
    "cherry",
    "chevron-down",
    "chevron-right",
    "chrome",
    "church",
    "cigarette",
    "circle",
    "circuit-board",
    "citrus",
    "clapperboard",
    "clipboard",
    "clock",
    "cloud",
    "cloud-download",
    "clover",
    "club",
    "code",
    "codepen",
    "codesandbox",
    "coffee",
    "cog",
    "coins",
    "columns2",
    "combine",
    "command",
    "compass",
    "component",
    "computer",
    "concierge-bell",
    "cone",
    "construction",
    "contact",
    "container",
    "contrast",
    "cookie",
    "cooking-pot",
    "copy",
    "copyleft",
    "copyright",
    "corner-down-left",
    "corner-up-right",
    "cpu",
    "creative-commons",
    "credit-card",
    "croissant",
    "crop",
    "cross",
    "crosshair",
    "crown",
    "cuboid",
    "cup-soda",
    "currency",
    "cylinder",
    "dam",
    "database",
    "delete",
    "dessert",
    "diameter",
    "diamond",
    "dices",
    "diff",
    "disc",
    "divide",
    "dna",
    "dock",
    "dog",
    "dollar-sign",
    "donut",
    "door-open",
    "dot",
    "download",
    "drafting-compass",
    "drama",
    "dribbble",
    "drill",
    "droplet",
    "drum",
    "drumstick",
    "dumbbell",
    "ear",
    "earth",
    "eclipse",
    "egg",
    "ellipsis",
    "equal",
    "eraser",
    "ethernet-port",
    "euro",
    "expand",
    "external-link",
    "eye",
    "facebook",
    "factory",
    "fan",
    "fast-forward",
    "feather",
    "fence",
    "ferris-wheel",
    "figma",
    "file",
    "files",
    "film",
    "filter",
    "filter-x",
    "fingerprint",
    "fire-extinguisher",
    "fish",
    "flag",
    "flame",
    "flashlight",
    "flask-conical",
    "flip-horizontal",
    "flip-vertical",
    "flower",
    "focus",
    "fold-horizontal",
    "fold-vertical",
    "folder",
    "folders",
    "footprints",
    "forklift",
    "forward",
    "frame",
    "framer",
    "frown",
    "fuel",
    "fullscreen",
    "gallery-horizontal",
    "gamepad",
    "gauge",
    "gavel",
    "gem",
    "ghost",
    "gift",
    "git-branch",
    "git-commit-horizontal",
    "git-compare",
    "git-fork",
    "git-graph",
    "git-merge",
    "git-pull-request",
    "github",
    "gitlab",
    "glass-water",
    "glasses",
    "globe",
    "goal",
    "grab",
    "graduation-cap",
    "grape",
    "grid2x2",
    "grip",
    "group",
    "guitar",
    "ham",
    "hammer",
    "hand",
    "hand-helping",
    "handshake",
    "hard-drive",
    "hard-hat",
    "hash",
    "haze",
    "hdmi-port",
    "heading",
    "headphones",
    "heart",
    "heart-off",
    "heater",
    "hexagon",
    "highlighter",
    "history",
    "hop",
    "hospital",
    "hotel",
    "hourglass",
    "house",
    "house-plug",
    "house-plus",
    "house-wifi",
    "ice-cream-bowl",
    "ice-cream-cone",
    "id-card",
    "image",
    "image-down",
    "image-minus",
    "image-off",
    "image-play",
    "image-plus",
    "image-up",
    "image-upscale",
    "images",
    "import",
    "inbox",
    "indent-decrease",
    "indent-increase",
    "indian-rupee",
    "infinity",
    "info",
    "inspection-panel",
    "instagram",
    "italic",
    "iteration-ccw",
    "iteration-cw",
    "japanese-yen",
    "joystick",
    "kanban",
    "key",
    "keyboard",
    "lamp",
    "land-plot",
    "landmark",
    "languages",
    "laptop",
    "lasso",
    "laugh",
    "layers",
    "layout-grid",
    "leaf",
    "lectern",
    "letter-text",
    "library",
    "life-buoy",
    "ligature",
    "lightbulb",
    "link",
    "linkedin",
    "list",
    "list-check",
    "list-plus",
    "loader",
    "locate",
    "lock",
    "lock-open",
    "log-in",
    "log-out",
    "logs",
    "lollipop",
    "luggage",
    "magnet",
    "mail",
    "mailbox",
    "mails",
    "map",
    "map-pin",
    "mars",
    "mars-stroke",
    "martini",
    "maximize",
    "medal",
    "megaphone",
    "meh",
    "memory-stick",
    "menu",
    "merge",
    "message-circle",
    "mic",
    "microchip",
    "microscope",
    "microwave",
    "milestone",
    "milk",
    "minimize",
    "minus",
    "monitor",
    "moon",
    "mountain",
    "mouse",
    "move-left",
    "move-right",
    "move-up",
    "move-down",
    "music",
    "navigation",
    "network",
    "newspaper",
    "nfc",
    "non-binary",
    "notebook",
    "notepad-text",
    "nut",
    "octagon",
    "omega",
    "option",
    "orbit",
    "origami",
    "package",
    "package-plus",
    "paintbrush",
    "palette",
    "panel-bottom",
    "panel-left",
    "panel-right",
    "panel-top",
    "panels-left-bottom",
    "panels-right-bottom",
    "panels-top-left",
    "paperclip",
    "parentheses",
    "parking-meter",
    "party-popper",
    "pause",
    "paw-print",
    "pc-case",
    "pen",
    "pencil",
    "pentagon",
    "percent",
    "person-standing",
    "philippine-peso",
    "phone",
    "pi",
    "piano",
    "pickaxe",
    "picture-in-picture",
    "piggy-bank",
    "pilcrow",
    "pill",
    "pill-bottle",
    "pin",
    "pipette",
    "pizza",
    "plane",
    "play",
    "plug",
    "plus",
    "pocket",
    "pocket-knife",
    "podcast",
    "pointer",
    "popcorn",
    "popsicle",
    "pound-sterling",
    "power",
    "presentation",
    "printer",
    "projector",
    "proportions",
    "puzzle",
    "pyramid",
    "qr-code",
    "quote",
    "rabbit",
    "radar",
    "radiation",
    "radical",
    "radio",
    "radius",
    "rail-symbol",
    "rainbow",
    "rat",
    "ratio",
    "receipt",
    "rectangle-horizontal",
    "recycle",
    "redo",
    "refresh-ccw",
    "refresh-cw",
    "refrigerator",
    "regex",
    "remove-formatting",
    "repeat",
    "replace",
    "reply",
    "rewind",
    "ribbon",
    "rocket",
    "rocking-chair",
    "roller-coaster",
    "rotate-ccw",
    "rotate-cw",
    "rotate3d",
    "route",
    "router",
    "rows2",
    "rss",
    "ruler",
    "russian-ruble",
    "sailboat",
    "salad",
    "sandwich",
    "satellite",
    "satellite-dish",
    "save",
    "scale",
    "scale3d",
    "scaling",
    "scan",
    "school",
    "scissors",
    "screen-share",
    "scroll",
    "search",
    "section",
    "send",
    "send-to-back",
    "separator-horizontal",
    "separator-vertical",
    "server",
    "settings",
    "shapes",
    "share",
    "sheet",
    "shell",
    "shield",
    "ship",
    "ship-wheel",
    "shirt",
    "shopping-cart",
    "shovel",
    "shower-head",
    "shrink",
    "shrub",
    "shuffle",
    "sigma",
    "signal",
    "signature",
    "signpost",
    "siren",
    "skip-back",
    "skip-forward",
    "skull",
    "slack",
    "slash",
    "slice",
    "sliders-horizontal",
    "smartphone",
    "smile",
    "snail",
    "snowflake",
    "sofa",
    "soup",
    "space",
    "spade",
    "sparkles",
    "speaker",
    "speech",
    "spell-check",
    "spline",
    "split",
    "spray-can",
    "sprout",
    "square",
    "squircle",
    "squirrel",
    "stamp",
    "star",
    "step-forward",
    "stethoscope",
    "sticker",
    "sticky-note",
    "store",
    "stretch-horizontal",
    "strikethrough",
    "subscript",
    "sun",
    "superscript",
    "swatch-book",
    "swiss-franc",
    "switch-camera",
    "sword",
    "swords",
    "syringe",
    "table",
    "tablet",
    "tag",
    "tally1",
    "tangent",
    "target",
    "telescope",
    "tent",
    "terminal",
    "test-tube",
    "text",
    "theater",
    "thermometer",
    "thumbs-down",
    "thumbs-up",
    "ticket",
    "timer",
    "toggle-right",
    "toilet",
    "tornado",
    "torus",
    "touchpad",
    "tower-control",
    "toy-brick",
    "tractor",
    "traffic-cone",
    "train-front",
    "transgender",
    "trash",
    "tree-pine",
    "trello",
    "trending-down",
    "trending-up",
    "trending-up-down",
    "triangle",
    "trophy",
    "truck",
    "turtle",
    "tv",
    "twitch",
    "twitter",
    "type",
    "umbrella",
    "underline",
    "undo",
    "unfold-horizontal",
    "unfold-vertical",
    "ungroup",
    "university",
    "unlink",
    "unplug",
    "upload",
    "usb",
    "user",
    "users",
    "utensils",
    "utility-pole",
    "variable",
    "vault",
    "vegan",
    "venetian-mask",
    "venus",
    "venus-and-mars",
    "vibrate",
    "video",
    "videotape",
    "view",
    "voicemail",
    "volleyball",
    "volume",
    "vote",
    "wallet",
    "wallpaper",
    "wand",
    "warehouse",
    "washing-machine",
    "watch",
    "waves",
    "waypoints",
    "webcam",
    "webhook",
    "weight",
    "wheat",
    "whole-word",
    "wifi",
    "wind",
    "wind-arrow-down",
    "wine",
    "workflow",
    "worm",
    "wrap-text",
    "wrench",
    "x",
    "youtube",
    "zap",
    "zap-off",
    "zoom-in",
    "zoom-out",
]


async def generate_icon_and_colors(name: str, description: str = "") -> dict[str, str]:
    """
    生成适当的图标和颜色方案。

    参数:
        name: 智能体/项目的名称
        description: 可选的描述，用于提供更完整的上下文

    返回:
        dict[str, str] 包含键: icon_name, icon_color, icon_background
    """
    logger.debug(f"正在为{name}生成图标和配色")
    try:
        model_name = "glm-4.6"

        frontend_colors = [
            "#000000",
            "#FFFFFF",
            "#6366F1",
            "#10B981",
            "#F59E0B",
            "#EF4444",
            "#8B5CF6",
            "#EC4899",
            "#14B8A6",
            "#F97316",
            "#06B6D4",
            "#84CC16",
            "#F43F5E",
            "#A855F7",
            "#3B82F6",
        ]

        context = f"Name: {name}"
        if description:
            context += f"\nDescription: {description}"

        system_prompt = f"""You are a helpful assistant that selects appropriate icons and colors for AI agents based on their name and description.

Available Lucide React icons to choose from:
{", ".join(RELEVANT_ICONS)}

Available colors (hex codes):
{", ".join(frontend_colors)}

Respond with a JSON object containing:
- "icon": The most appropriate icon name from the available icons
- "background_color": A background color hex code from the available colors
- "text_color": A text color hex code from the available colors (choose one that contrasts well with the background)

Example response:
{{"icon": "youtube", "background_color": "#EF4444", "text_color": "#FFFFFF"}}"""

        user_message = f"Select the most appropriate icon and color scheme for this AI agent:\n{context}"
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ]

        logger.debug(f"正在调用 {model_name} 生成图标和配色。")
        response = await make_llm_api_call(
            messages=messages,
            model_name=model_name,
            stream=False,
            system_prompt=system_prompt,
            prompt=user_message,
            output_format={
                "type": "json_schema",
                "schema": {
                    "icon": {"type": "string", "enum": RELEVANT_ICONS},
                    "background_color": {"type": "string", "enum": frontend_colors},
                    "text_color": {"type": "string", "enum": frontend_colors},
                },
            },
        )

        # 默认回退值
        result = {
            "icon_name": "bot",
            "icon_color": "#FFFFFF",
            "icon_background": "#6366F1",
        }

        if response and isinstance(response, dict) and response.get("result"):
            raw_content = response["result"].strip()
            try:
                parsed_response = json.loads(raw_content)

                if isinstance(parsed_response, dict):
                    # 提取并验证图标
                    icon = parsed_response.get("icon", "").strip()
                    if icon and icon in RELEVANT_ICONS:
                        result["icon_name"] = icon
                        logger.debug(f"已选定图标：'{icon}'")
                    else:
                        logger.warning(f"选中的图标'{icon}'无效，使用默认图标'bot'")

                    # 提取并验证颜色
                    bg_color = parsed_response.get("background_color", "").strip()
                    text_color = parsed_response.get("text_color", "").strip()

                    if bg_color in frontend_colors:
                        result["icon_background"] = bg_color
                        logger.debug(f"已选定背景色：'{bg_color}'")
                    else:
                        logger.warning(f"选中的背景色'{bg_color}'无效，使用默认背景色")

                    if text_color in frontend_colors:
                        result["icon_color"] = text_color
                        logger.debug(f"已选定文字颜色：'{text_color}'")
                    else:
                        logger.warning(f"选中的文字颜色'{text_color}'无效，使用默认文字颜色")

                else:
                    logger.warning(f"返回非字典类型JSON: {parsed_response}")

            except json.JSONDecodeError as e:
                logger.warning(f"解析 JSON 响应失败：{e}。 原始内容：{raw_content}")
        else:
            logger.warning(f"未能获得有效的图标生成结果，返回内容：{response}")

        logger.debug(
            f"已生成样式：图标={result['icon_name']}，背景={result['icon_background']}，颜色={result['icon_color']}"
        )
        return result

    except Exception as e:
        logger.error(f"图标生成错误：{str(e)}\n{traceback.format_exc()}")
        # 返回默认值
        return {
            "icon_name": "bot",
            "icon_color": "#FFFFFF",
            "icon_background": "#6366F1",
        }
